# Generated by Django 5.1.12 on 2025-09-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(db_index=True, max_length=20)),
                ('method', models.CharField(choices=[('sms', 'SMS'), ('call', 'CALL')], db_index=True, max_length=8)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('last4_expected', models.CharField(blank=True, max_length=4, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ua', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_e164', 'used', 'created_at'], name='apps_auth_p_phone_e_1975c2_idx')],
            },
        ),
    ]
