http:
  routers:
    # Эти роуты начнут работать, когда появятся контейнеры backend/frontend (выше в compose)
    backend:
      entryPoints: [ web ]
      rule: Host(`backend.localhost`)
      service: backend
    frontend:
      entryPoints: [ web ]
      rule: Host(`frontend.localhost`)
      service: frontend

  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8000"      # порт приложения внутри контейнера
    frontend:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"
